// Generated by CoffeeScript 2.3.2
(function() {
  //###############################################################################
  // Modules Variable carrying all external Modules
  //###############################################################################
  var Modules, app;

  Modules = {
    express: require('express')
  };

  //###############################################################################
  // Initialization
  //###############################################################################
  app = Modules.express();

  app.use(Modules.express.static('website'));

  //###############################################################################
  // Start listening
  //###############################################################################
  app.listen(3000, function() {
    console.log('ready listening on localhost:3000');
  });

}).call(this);
